# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-156092728-2'

menu:
#- {name: 'about',              url: 'index'}
- {name: 'articles',           url: 'articles'}
- {name: 'libraries',          url: 'libraries'}
- {name: 'design',             url: 'design'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {name: 'Twitter', icon: 'twitter', link: 'https://twitter.com/nickmuse'}
- {name: 'GitHub',  icon: 'github',  link: 'https://github.com/nickmuse'}
- {name: 'Medium',  icon: 'medium',  link: 'https://medium.com/@nickmuse'}
- {name: 'itch.io', icon: 'itch-io', link: 'https://nickmuse.itch.io'}
#- {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
#- {icon: 'instagram', link:  'https://instagram.com/paululele'}
#- {icon: 'envelope', link:   'mailto:hello@paulle.ca'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'newer'
  previous_page: 'older'

hide_post_date: false

sharing_button_prompt: 'Share this'
hide_post_share: true

related_posts: 'You may also enjoy...'
hide_related_posts: true

post_date_prefix: 'Created on'

bottom_line: '2023 Nick Muse'
